### ISSUE TITLE
Refactor InlineGenerator -> Remove type hints in new class

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#119]
Currently, the InlineGenerator adds tracing type hints & removes existing type hints. This is useful for evaluation. However, in production we only want to add the tracing type hints without changing existing type hints. Thus, a subclass of the corresponding AST Transformer should be created which does both, while the current AST Transformer only adds the tracing type hints.

**Comment by bengsparks** [comment]
In addition thereto, in "production" mode, "public" typed attributes can be added to each class.
public attributes can be recognised if they do not have a leading underscore, i.e. `_attr` is not-public, `attr` is public

**Comment by RecurvedBow** [comment]
In production mode, all existing type hints are kept & traced type hints are added if no type hint for the variable exist. In evaluation, the existing type hints are dropped before adding the traced type hints. This allows us to compare original type hints and traced type hints and thus evaluate the tracer.
