### ISSUE TITLE
Add TracerBase to determine min speed time of Tracer

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#125]
Create a base class Tracer base which only returns _on_trace_is_called in _on_trace_is_called(). The class is used to determine the min time of tracing a function. All tracer are as slow or slower than the tracer base regarding the speed. This is useful to determine which time is spent for getting the frame call and how much time is actually spent in _on_trace_is_called.

**Comment by bengsparks** [comment]
Moved to next milestone. This sprint is already full enough.
