### ISSUE TITLE
Remove outliers & apply linear regression of performance data in jupyter notebook file

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#126]
Requires #63 to get more data.

Other methods of regression can also work, but a relationship between standard time & tracing time has to be determined. As we expect tracing_time = m * standard_time + c, linear regression should be the most fitting algorithm.

**Comment by bengsparks** [comment]
Moved to next milestone. This sprint is already full enough.

**Comment by RecurvedBow** [comment]
#63 shows that linear regression is not possible as the data is too spread apart. Analysis about data and outliers have been made.
