### ISSUE TITLE
Fix test_pytest_features.py

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#152]
![image](https://user-images.githubusercontent.com/101172476/185393085-4aad4c00-464f-4128-a06b-a3c7aef19766.png)

Currently, the tests use the actual project config file. Instead of using the actual project config, mock the config used by the decorators.

**Comment by bengsparks** [comment]
Ah, it looks like I accidentally committed my pytypes.toml :sweat_smile:
