### ISSUE TITLE
Update main to evaluate projects with evaluation command

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#157]
Given a project and its tracedata,  tygegen __init__ main should: 
1. Collect the trace data (Already implemented)
2. Process it using the filters (Already implemented)
3. Generate the files with traced type hints  (Already implemented)
4. Compare the original with the generated file (Classes implemented, but usage missing)
5. Get the metric data (Classes implemented, but usage missing)

Implement step 4 and 5.

**Comment by bengsparks** [comment]
[I have a branch for this already](https://github.com/pvs-hd-tea/PyTypes/tree/enhm/pytest-requirements). It's missing the metric data usage though. 
Feel free to update it as you implemented the metric perfomance

**Comment by RecurvedBow** [comment]
It looks like this branch only includes pytest requirements + refactors. However, if I see this correctly, it does not implement anything regarding evaluation in typegen main. Will start work on this issue if this branch has been merged.

**Comment by RecurvedBow** [comment]
Will be done together with #160

**Comment by bengsparks** [comment]
After discussion: A new subcommand will be created called `evaluation` that consumes the original and the generated project
