### ISSUE TITLE
Fix Inline Generator for multi-line function def

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#203]
![image](https://user-images.githubusercontent.com/101172476/187063208-46521332-db11-425f-a3fb-c576bb814505.png)

Parameters are not appended if the function definition is longer than one line. Fix this.

**Comment by bengsparks** [comment]
This issue most likely stems from the tracer gathering the parameters of arguments when we enter the function, i.e. on the  `call` event, and using the function's line number for the parameters. A good fix would be to ignore the line number when generating annotations for parameters, as the function name + parameter name should be sufficient to identify the correct annotation
