### ISSUE TITLE
Associate class members with the class / Enhance inference in methods 

### ISSUE THREAD

**Issue by bengsparks** [pvs-hd-tea/PyTypes#26]
Given a class

```python
class Clazz:
    def __init__(self, x, y):
        self.x = x
        self.y = y
```

The types of `self.x` and `self.y` can currently be inferred by checking the types of arguments passed to the `__init__` constructor;
However, they do not associate the instance of `x` belonging to `Clazz`.
This is necessary for inference of class members to work correctly.

**Comment by bengsparks** [comment]
Check the `inspect` module for `is*` methods, e.g. `ismethod`, `isfunction`. etc.

**Comment by RecurvedBow** [comment]
Turned into #30
