### ISSUE TITLE
Find a way to trace test functions in files

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#40]
Given pytest test functions in files in the project, find a way to execute them and collect the trace data.

Options: 
- Add the decorators to the test functions and set the entry points
- Develop a test function collector which searches for the test functions and stores them in a collection

**Comment by bengsparks** [comment]
Applying the decorators to the functions in question already stores the functions you need.
We will probably need to create a script that parses all test functions into in-memory ASTs, apply the decorator to them, and write the modified source code back into the file.

**Comment by RecurvedBow** [comment]
Problem is that once it is applied, it can not be easily reverted. If the decorators are applied, but we change the script, the hooks have to be removed so that the script can be tested again.

Well, let's see.

**Comment by bengsparks** [comment]
Why would we have to remove the decorators?
