### ISSUE TITLE
Make pytypes.toml not mandatory for pytest functions

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#42]
For some reason, a pytypes.toml file is neccessary to execute pytest unit test functions. Check out examples/tests/test_simple.py. Removing the toml file in the same file causes the tests to fail.

Either fix this or provide an alternative to avoid manually adding this toml files for each pytest file.

**Comment by RecurvedBow** [comment]
The autogenerated pytypes.toml is in the wrong folder. When attempting to run generated tests on the numpy repository, the generated pytypes.toml is in the root of the repo. The test however requires the toml file to be in the test folder.

**Comment by bengsparks** [comment]
Development has proceeded just fine without this. Closing
