### ISSUE TITLE
Deserialize trace data files & fuse into one dataframe

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#45]

**Comment by bengsparks** [comment]
This will most likely be part of a later milestone, probably [Further Processing of Tracing Data](https://github.com/pvs-hd-tea/PyTypes/milestone/4). Thoughts? @RecurvedBow

**Comment by RecurvedBow** [comment]
Well, this issue is actually pretty small. We only need to search for serialized trace data files and combine them into one single dataframe.

Desc: Given serialized trace data files generated from the decorators, deserialize them and combine them into a single dataframe. This can be used for further processing.

**Comment by bengsparks** [comment]
This is not a priority right now, and you still have a research task to do for this sprint I believe :p

**Comment by RecurvedBow** [comment]
Already working on the research task.

We can create such an issue if we encounter memory issues in the future.
