### ISSUE TITLE
Refactoring the DecoratorAppender into PyTestStrategy

### ISSUE THREAD

**Issue by bengsparks** [pvs-hd-tea/PyTypes#54]
Currently, the `DecoratorAppender` class, while functional, does not conform to the style implemented by #46; it should be moved into the `PyTestStrategy` class. 
Also, we need to talk about the automated execution of test files; this should probably be split into a separate class.

Because this requires understanding within the team, both members have been assigned, but only one should implement this, as it is not a large task. I will probably do this, because @RecurvedBow still has a [research task](https://github.com/pvs-hd-tea/PyTypes/issues/9) open that is due by the end of this sprint.

**Comment by RecurvedBow** [comment]
The appender appends the decorators to files in a project folder. So if my understanding is correct, you only have to move the implementation of appender.append_decorator_on_all_files_in to strategy.apply. 

Please also refactor the existing appender tests.
