### ISSUE TITLE
Drop trace data if tracer encounters (Type) Error frame

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#55]
The trace data of a function which has encountered an type error has to be removed as this means that at least one variable is of the wrong type. Keeping such data would lead to wrong type inference. To avoid checking which errors also cause the trace data to be removed, generalize this and delete the data of the function if it encounters any error.

**Comment by bengsparks** [comment]
We need to be careful to only catch exceptions that do not propagate into the test code, i.e. unexpected exceptions.
Because tests in these repositories are written to pass, this will probably rarely occur, maybe never

**Comment by bengsparks** [comment]
I am doubtful that these kinds of tests are written. Let's review our chosen repositories soon, see what the tests check for

**Comment by RecurvedBow** [comment]
Yeah, we might have to move this to evaluation. If the exception is caught within the same function, then we should keep the trace data.

**Comment by bengsparks** [comment]
Moving to Evaluation II, where we can see if this ever becomes relevant.

**Comment by bengsparks** [comment]
Never became relevant, closing
