### ISSUE TITLE
Move test file execution to new class

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#58]
Create a trace data generator/stategy-execution class which contains the execution of the trace data files. It should accept list[pathlib.path] and generate trace data files.

**Comment by bengsparks** [comment]
Perhaps we should even consider not automating this, and simply rely upon manually executing the test command in the repo's folder.
Especially concerning resource acquisition and dependency installation, this can become non-trivial.

**Comment by RecurvedBow** [comment]
But will the decorator hooks work if we execute it manually? Their implementation is not in the repo folder.

**Comment by bengsparks** [comment]
Yes, as long as we extend `sys.path` to include our project, we can use the decorators. We will also have to overwrite the tests now, instead of creating new ones

**Comment by RecurvedBow** [comment]
I see, this might work. I will leave it to you.

Also remove the current execution implementation if it is not needed anymore.
