### ISSUE TITLE
Check case why decorators return wrong trace data

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#64]
When testing the decorators on sample files, wrong trace data is generated. For example:
``` Python
class SampleClass:
    def __init__(self, integer1):
        self.integer1 = integer1

    def is_equivalent(self, integer1):
        return self.integer1 == integer1

@register()
def test_if_sample_class_is_equivalent_is_called_correct_equality_is_returned():
    test_object = SampleClass(4)
    assert test_object.is_equivalent(4)
    assert not test_object.is_equivalent(2)

@entrypoint()
def main():
  ...
```

The generated trace data file contains the following trace data:
``` Json
{
"Filename":{"0":"tracing\\tracer.py"},
"Function Name":{"0":"active_trace"},
"Line Number":{"0":39},
"Category":{"0":"TraceDataCategory.FUNCTION_ARGUMENT"},
"Name":{"0":"self"},
"Type":{"0":{}}
}
```

Find out why and fix it.

**Comment by RecurvedBow** [comment]
The issue was discovered when running an older commit containing the decorator appender. By printing the trace data in the decorators, the bug was found.

**Comment by bengsparks** [comment]
This occurs because the decorators calls `active_trace` on the Tracer, which in turns automatically calls `start_` and `stop_` trace. Simply adding another drop to the `Tracer.active_trace` method should suffice.

**Comment by bengsparks** [comment]
This will likely be fixed due to a change in how the Tracer determines what to drop where.
Check #67

**Comment by RecurvedBow** [comment]
Renamed this issue as correct trace data is indeed collected by the decorators (using the fetch command), but fails for the provided case. Found out why the resulting trace data in this case is invalid.
