### ISSUE TITLE
Benchmark effects of optimisations

### ISSUE THREAD

**Issue by bengsparks** [pvs-hd-tea/PyTypes#68]
How much time do our optimisations save? Do they save time at all? Their implementation is non-trivial, perhaps this needs to be simplified

**Comment by RecurvedBow** [comment]
I recommend implementing #88 first.

**Comment by RecurvedBow** [comment]
Will do this by creating a register_with_performance decorator which also returns the time elapsed of the function, with the standard tracer & with the optimized tracer. The execution will be repeated 10 times to determine the mean & std. The values will be serialized and will be collected by a class which serializes the collected values in one file. Finally, the data is analyzed using a Jupyter Notebook.

**Comment by RecurvedBow** [comment]
An implementation for evaluating the speed has been made. However, it requires more data, for example from #63 .

**Comment by bengsparks** [comment]
Continuing in Evaluation II

**Comment by RecurvedBow** [comment]
Results are in #63 . Summary: On average, the standard tracer is faster than the optimized tracer. It is recommended to disable optimizations of the tracer #205.
