### ISSUE TITLE
Fix filename values of trace data

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#7]
Depending on the computer/OS/system, the "/" in file path of the tracing data is in one computer "/", in the other "\\".

Ensure that the string file path stays the same, regardless of the system.

**Comment by bengsparks** [comment]
Look into using https://docs.python.org/3/library/pathlib.html for creating OS independent filepaths

**Comment by RecurvedBow** [comment]
Moved back to open since #19 needs to be resolved first
