### ISSUE TITLE
Add more filters

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#81]
Add filters which are useful. If there are results in #74 , then use the insights to create more filters. 

Keep the issue open until the end of this sprint.

**Comment by RecurvedBow** [comment]
Will implement: Drop Test Function Data Filter. Drops data about test functions.

**Comment by bengsparks** [comment]
Is there a statistical filter? e.g. when 99% of usages of a variable occur with data type T, and 1% of usages occur with data type U, then we simply drop U?

**Comment by RecurvedBow** [comment]
We could implement that.

**Comment by RecurvedBow** [comment]
Additionally, implement UnionMultipleTypesFilter & NormalizeFilter (Optional[type] -> type | None, Union[a, b] -> a | b, ...)

**Comment by RecurvedBow** [comment]
Will also implement keep first filter. The inline generator expects for each variable in the trace data to have exactly one type. If the trace data has for each variable only one type, the keep first filter won't change the data.
