### ISSUE TITLE
Move optimizations of tracer into new class: OptimizedTracer

### ISSUE THREAD

**Issue by RecurvedBow** [pvs-hd-tea/PyTypes#88]
To benchmark the tracer & its optimizations, create a class OptimizedTracer which contains the current implementation of the tracer & derives from (non-optimized) Tracer class, which contains no optimizations. This allows better benchmarking of the optimizations.

**Comment by bengsparks** [comment]
Or simply pass a constructor flag to the tracer, that is defaulted to True, such as `apply_opts`

**Comment by RecurvedBow** [comment]
Alright, will do that.
